pub const STR_INVALID_WIN_WIDE_OS_STR: &str = "InvalidWinWideOsStr";

pub const RAWINPUT_MSG_INIT_BUF_SIZE: u32 = 1024;
pub const RATELIMIT_UPDATE_MONITOR_ONCE_MS: u64 = 1000;
pub const RATELIMIT_UPDATE_DEVICE_ONCE_MS: u64 = 1000;
