name: Build
on:
  workflow_call:
    inputs:
      version_anno:
        type: string
        default: ""
      upload_name:
        type: string
        default: ""
      release_name:
        type: string
        default: ""
      use_dep_cache:
        type: boolean
        default: true
env:
  CARGO_TERM_COLOR: always
  VERSION_ANNO: ${{ inputs.version_anno }}
  VERSION_SHA: ${{ github.sha }}
jobs:
  dep-cache:
    if: inputs.use_dep_cache
    uses: ./.github/workflows/build-dep.yml
  build-and-upload:
    runs-on: windows-latest
    needs: [dep-cache]
    if: |
      always() &&
      (needs.dep-cache.result == 'success' || needs.dep-cache.result == 'skipped')
    steps:
    - name: Checkout source
      uses: actions/checkout@v4
    - name: Restore dep cache
      if: inputs.use_dep_cache
      uses: actions/cache/restore@v4
      with:
        path: |
          ~/.cargo/registry
          ~/.cargo/git
          target
        key: dep-cache-${{ hashFiles('Cargo.lock') }}-${{ runner.os }}
        fail-on-cache-miss: true
    - name: Build
      shell: cmd
      run: |      
        for /f "delims=" %%i in ('powershell.exe "scripts\get_rc_path.ps1"') do set RC_EXEC=%%i
        echo RC_EXEC set to %RC_EXEC%
        cargo build --release
    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      if: inputs.upload_name != ''
      with:
        name: monmouse-${{ inputs.upload_name }}-windows
        path: |
          target/release/monmouse.exe
          target/release/monmouse-cli.exe
          - name: Releases
    - name: Pack
      if: inputs.release_name != ''
      run: cd target\release && tar -caf monmouse-${{ inputs.release_name }}-windows.zip monmouse.exe monmouse-cli.exe
    - name: Upload release assets
      uses: softprops/action-gh-release@v2
      if: inputs.release_name != ''
      with:
        body: |
          [CHANGELOG](https://github.com/melon-masou/MonMouse/blob/${{ inputs.release_name }}/CHANGELOG.md)
        draft: true
        files: |
          target/release/monmouse-${{ inputs.release_name }}-windows.zip