name: Check
on:
  push:
    branches:
      - '*'
  pull_request:
  workflow_dispatch:
jobs:
  check:
    uses: ./.github/workflows/build.yml
    with:
      version_anno: "check"
      use_dep_cache: true