name: Snapshot
on:
  push:
    tags:
      - 'v*'
jobs:
  release:
    uses: ./.github/workflows/build.yml
    with:
      version_anno: "release"
      upload_name: ${{ github.ref_name }}
      use_dep_cache: false