name: Release
on:
  push:
    tags:
      - 'v*.*.*'
jobs:
  release:
    uses: ./.github/workflows/build.yml
    with:
      version_anno: "release"
      release_name: ${{ github.ref_name }}
      use_dep_cache: false