name: Snapshot
on: workflow_dispatch
env:
  CARGO_TERM_COLOR: always
jobs:
  build:
    uses: ./.github/workflows/build.yml
    with:
      version_anno: "snapshot"
      upload_name: ${{ github.sha }}
      use_dep_cache: true