name: Snapshot
on: workflow_dispatch
env:
  CARGO_TERM_COLOR: always
jobs:
  build-dep:
    uses: ./.github/workflows/build-dep.yml
  snapshot:
    runs-on: windows-latest
    needs: [build-dep]
    steps:
    - name: Restore dep cache
      uses: actions/cache/restore@v4
      with:
        path: |
          ~/.cargo/registry
          ~/.cargo/git
          target
        key: dep-cache-${{ hashFiles('Cargo.lock') }}-${{ runner.os }}
    - name: Checkout source
      uses: actions/checkout@v4
    - name: Build
      run: cargo build --release
    - name: Pack
      run: cd target\release && tar -caf monmouse.zip monmouse.exe monmouse-cli.exe
    - name: Upload
      uses: actions/upload-artifact@v4
      with:
        name: monmouse-${GITHUB_SHA::7}-windows
        path: target/release/monmouse.zip